setwd("C:/Users/CORE i3 IN/Downloads")
library(arules)
books <- read.transactions(file.choose(), format ="basket")
View(books)
inspect(books[1:15])
itemFrequencyPlot(books, topN = 5)
book_rules <- apriori(books,parameter = list(support = 0.002,confidence = 0.05,minlen=3))
library(arulesViz)
plot(book_rules,method = "scatterplot")
plot(book_rules,method = "grouped")
plot(groceries_rules,method = "graph")
plot(groceries_rules,method = "mosaic")
